import curses
import time
import random

def balloon(screen):
    x = random.randrange(15,55)
    screen.addstr(curses.LINES - 1,x,"          **")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 2,x,"         ***")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 3,x,"          **")
    screen.addstr(curses.LINES - 4,x,"        *  **")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 5,x,"      *  ***x **")
    screen.addstr(curses.LINES - 6,x,"    x***+x* *  **")
    screen.addstr(curses.LINES - 7,x,"   +******x+x++x **")
    screen.refresh()
    time.sleep(0.09)
    screen.addstr(curses.LINES - 8,x,"  *****+x++x*x++ *  **")
    screen.addstr(curses.LINES - 9,x,"  *****+x++x*x++ *  **")
    screen.addstr(curses.LINES - 10,x,"   +******x+x++x **")
    screen.refresh()
    time.sleep(0.09)
    screen.addstr(curses.LINES - 11,x,"    x***+x* *  **")
    screen.addstr(curses.LINES - 12,x,"         *x **")
    time.sleep(0.1)
    screen.refresh()
    screen.addstr(curses.LINES - 1,x,"          *   ")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 2,x,"            ")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 3,x,"          * ")
    screen.addstr(curses.LINES - 4,x,"        *    ")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 5,x,"         **x     ")
    screen.addstr(curses.LINES - 6,x,"    * * **     *")
    screen.addstr(curses.LINES - 7,x,"   +***         **")
    screen.refresh()
    time.sleep(0.09)
    screen.addstr(curses.LINES - 8,x,"  **   ** *      **")
    screen.addstr(curses.LINES - 9,x,"  *****    *   *  *")
    screen.addstr(curses.LINES - 10,x,"   +******x+    **")
    time.sleep(0.1)
    screen.refresh()
    screen.addstr(curses.LINES - 11,x,"    x**  x* *  **")
    screen.addstr(curses.LINES - 12,x,"         *x  *")
    time.sleep(0.1)
    screen.refresh()
    screen.addstr(curses.LINES - 1,x,"              ")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 2,x,"            ")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 3,x,"            ")
    screen.addstr(curses.LINES - 4,x,"             ")
    screen.refresh()
    time.sleep(0.1)
    screen.addstr(curses.LINES - 5,x,"                 ")
    screen.addstr(curses.LINES - 6,x,"              *")
    screen.addstr(curses.LINES - 7,x,"                      ")
    screen.refresh()
    time.sleep(0.09)
    screen.addstr(curses.LINES - 8,x,"                       *")
    screen.addstr(curses.LINES - 9,x,"  *                          ")
    screen.addstr(curses.LINES - 10,x,"   +**                    ")
    time.sleep(0.1)
    screen.refresh()
    screen.addstr(curses.LINES - 11,x,"    x**  x* *  **")
    screen.addstr(curses.LINES - 12,x,"         *x  *")
    time.sleep(0.1)
    screen.refresh()
    screen.addstr(curses.LINES - 6,x,"                      ")
    screen.addstr(curses.LINES - 7,x,"                       * ")
    screen.refresh()
    time.sleep(0.09)
    screen.addstr(curses.LINES - 8,x,"  *                        ")
    screen.addstr(curses.LINES - 9,x,"     **                      ")
    screen.addstr(curses.LINES - 10,x,"    *  * *  *              ")

    screen.addstr(curses.LINES - 11,x,"                   ")
    screen.addstr(curses.LINES - 12,x,"               ")
    screen.addstr(curses.LINES - 7,x,"                               ")
    screen.addstr(curses.LINES - 8,x,"                            ")
    screen.addstr(curses.LINES - 9,x,"                                  ")
    screen.addstr(curses.LINES - 10,x,"                          ")
    time.sleep(0.1)
    screen.refresh()
    screen.addstr(curses.LINES - 11,x,"                        ")
    screen.addstr(curses.LINES - 12,x,"                          ")

def start():
    return curses.wrapper(balloon)
